- name: SonarCloud Scan
  uses: SonarSource/sonarcloud-github-action@v2
  with:
    projectBaseDir: .
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_ORGANIZATION: anusha-star-dot
    SONAR_PROJECT_KEY: Anusha-star-dot_containerized-flask-app
